name: Unzip, Flatten, and Commit

on:
  push:
    branches:
      - main

jobs:
  unzip_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip the archive
        run: unzip -o BWM-XMD-QUANTUM-main.zip

      - name: Move contents to root and remove folder
        run: |
          shopt -s dotglob  # include hidden files
          rsync -a BWM-XMD-QUANTUM-main/ .
          rm -rf BWM-XMD-QUANTUM-main

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push unzipped content (excluding workflows)
        run: |
          git add .
          git reset .github/workflows || true  # unstage any workflow changes

          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Unzipped and moved contents of BWM-XMD-QUANTUM-main.zip to root [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
